name: flutter_banking_pay_responsive
description: Baking Pay responsive app by Pedro Santos | Built using Flutter :)

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  intl: ^0.17.0
  provider: ^6.0.2

  animated_text_kit: ^4.2.1
  app_settings: ^4.1.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.4
  flutter_speed_dial: ^5.0.0+1
  font_awesome_flutter: ^9.2.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  image_picker: ^0.8.4+4
  scrollable_positioned_list: ^0.2.3
  sliding_sheet: ^0.5.2
  share_plus: ^3.0.4
  shimmer: ^2.0.0
  url_launcher: ^6.0.18
  quick_actions: ^0.6.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_vector_icons: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo/app_logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/avatars/

#l10n and i18n
flutter_intl:
  enabled: true
  main_locale: en_US
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n
